// <auto-generated />
using System;
using Artistas.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Artistas.DAL.Migrations
{
    [DbContext(typeof(ArtistaContext))]
    [Migration("20200707210341_ArtistasInicial")]
    partial class ArtistasInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Artistas.DAL.Entities.Artista", b =>
                {
                    b.Property<int>("ArtistaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .HasMaxLength(80);

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Pais")
                        .HasMaxLength(80);

                    b.Property<string>("Site")
                        .HasMaxLength(80);

                    b.HasKey("ArtistaId");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("Artistas.DAL.Entities.ArtistaDetalhe", b =>
                {
                    b.Property<int>("ArtistaDetalheId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtistaId");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(255);

                    b.Property<string>("Talento")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("ArtistaDetalheId");

                    b.HasIndex("ArtistaId");

                    b.ToTable("ArtistaDetalhes");
                });

            modelBuilder.Entity("Artistas.DAL.Entities.ArtistaDetalhe", b =>
                {
                    b.HasOne("Artistas.DAL.Entities.Artista", "Artista")
                        .WithMany("ArtistaDetalhes")
                        .HasForeignKey("ArtistaId");
                });
#pragma warning restore 612, 618
        }
    }
}
